basic_packages:
  - bat
  - curl
  - docker
  - docker-compose
  - fzf
  - git
  - htop
  - lsof
  - lua5.3
  - mmv
  - make
  - python3-pip
  - python3-venv
  - ripgrep
  - rsync
  - stow
  - tree
  - ufw
  - zsh
